export const SET_INPUT_WORD = "SET_INPUT_WORD";
export const SET_CARD_DESCRIPTION = "SET_CARD_DESCRIPTION";
export const SET_IS_ADDITIONAL_CONTENT = "SET_IS_ADDITIONAL_CONTENT";
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_PENDING = "FETCH_DATA_PENDING";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
